# Generated by Django 2.2.5 on 2021-06-13 09:54
from django.conf import settings
from django.db import migrations
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0004_auto_20210612_0425'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='roomtype',
            options={'ordering': ['name'], 'verbose_name': 'Room Type'},
        ),
    ]

    operation = [
        migrations.AlterField(
            model_name="room",
            name="host",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                    related_name='rooms', to=settings.AUTH_USER_MODEL),
        ),
    ]
